version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  frontend:
    build:
          context: ./client/
          dockerfile: ./Dockerfile
    ports:
        - "8080:8080"
    command: "npm run serve"
    links:
        - "app"